name: cart
description: Cart package for GoRouter POC
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  go_router_builder: any
  build_runner: any
  build_verify: any

flutter:
  uses-material-design: true
